// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_500 = "CgkI1PPsl-0YEAIQBw"; // <GPGSID>
        public const string achievement_100 = "CgkI1PPsl-0YEAIQBg"; // <GPGSID>
        public const string achievement_50 = "CgkI1PPsl-0YEAIQBQ"; // <GPGSID>
        public const string leaderboard = "CgkI1PPsl-0YEAIQAw"; // <GPGSID>
        public const string achievement__100lv = "CgkI1PPsl-0YEAIQCQ"; // <GPGSID>
        public const string achievement_10000 = "CgkI1PPsl-0YEAIQCg"; // <GPGSID>
        public const string achievement_1000 = "CgkI1PPsl-0YEAIQCA"; // <GPGSID>
        public const string achievement_20 = "CgkI1PPsl-0YEAIQBA"; // <GPGSID>

}

